In [40]:
""""In these code you will able to understand how the MDP works, Beofre that for your informaton you can take a look at
https://www.csie.ntu.edu.tw/~b91046/meeting/m2/mdp.pdf for your concern about the Bellman equation 

What is q-learning?
Q-learning is an off policy reinforcement learning algorithm that seeks to find the best action to take given the current state

It’s considered off-policy because the q-learning function learns from actions that are outside the current policy,
like taking random actions, and therefore a policy isn’t needed. More specifically, q-learning seeks to learn a policy that 
maximizes the total reward.

The ‘q’ in q-learning stands for quality. Quality in this case represents how useful a given action is in gaining some future reward.

So then here we will see q learing  reinforcement learning with reward function

in these code we will import numpy library as ql

ql is an nxp matrix from A for QL decomposition

A is list of two matrices Q and L so that A = QL

Q - nxp matrix with orthonormal columns with the same span as A

L - is a lower triangular pxp matrix with nonnegative diagonal entries
________________________________________________________________________________________________________________________________________________________________________________
For MDP we will use two variable R as reward and Q as learininf Matrix

R - is reward matrix for each state

Q - is the Learning Matrix in which rewards will be learned/stored

""" 

import numpy as ql

# you can give your own matrix

R = ql.matrix([ [0,1,0,0,1,0],
                [0,1,0,1,0,1],
                [0,0,100,1,0,0],
                [0,1,1,0,1,0],
                [1,0,0,1,0,0],
                [0,1,0,0,100,0] ])


Q = ql.matrix(ql.zeros([6,6]))

"""
Gamma: gamma or γ is a discount factor. It’s used to balance immediate and future reward. From our update rule 
above you can see that we apply the discount to the future reward. Typically this value can range anywhere from 0.8 to 0.99.

"""
gamma = 0.8

"""
agent_s_state is the agent the name of the system calculating and s is the state and can be random number or it can be chosen
and random is part of this stochastic process
"""
agent_state = 3

# The possible "a" actions when the agent is in a given state
def possible_actions(state):
    current_state_row = R[state,]
    possible_act = ql.asarray(current_state_row > 0).nonzero()
    return possible_act[1] # Return the index of posibility

# Get action
PossibleAction = possible_actions(agent_s_state)

# This function chooses at random which action to be performed within the range 
# of all the available actions.
def ActionChoice(available_actions_range):
    if(sum(PossibleAction) > 0):
        next_action = int(ql.random.choice(PossibleAction,1))
    if(sum(PossibleAction) <= 0):
        next_action = int(ql.random.choice(5,1))
    return next_action


# Sample next action to be performed
action = ActionChoice(PossibleAction)
print('action',action)
print(Q[action,])

"""
A version of Bellman's equation for reinforcement learning using the Q function
This reinforcement algorithm is a memoryless process. The transition function T from one state to another
is not in the equation below. T is done by the random choice above 
print(Q[action,])

"""
# 
def reward(current_state, action, gamma):
    print('bf_Q',Q)

    Max_State = ql.asarray(Q[action,] == ql.max(Q[action,])).nonzero()[1]
    print('bf_max_state',Max_State)
    if Max_State.shape[0] > 1: # Check if max_state have more than 1 column
        Max_State = ql.random.choice(Max_State, size=1)
        print('max_state', Max_State)
    else:
        Max_State = int(Max_State)
    print('af_max_state',Max_State)
    MaxValue = Q[action, Max_State]
    print('max_value', MaxValue)
    # Bellman's MDP based Q function
    Q[current_state, action] = R[current_state, action] + gamma * MaxValue

# Rewarding the Q matrix
reward(agent_s_state, action, gamma)
print('reward',Q[agent_s_state,])
print('')
# Learning over n iterations depending on the convergence of the system
# A convergence function can replace the systematic repeating of the process
# by comparing the sum of the Q matrix to that of Q matrix n-1 in the
# previous episode
for i in range(25):
    current_state = ql.random.randint(0, int(Q.shape[0]))
    print('curr_state',current_state)
    PossibleAction = possible_actions(current_state)
    print('poss_act',PossibleAction)
    action = ActionChoice(PossibleAction)
    print('action',action)
    reward(current_state,action,gamma)
    print('reward',Q)
    print('')

#Displaying Q before the norm of Q phase
print(Q)

#Norm of Q
print("Normed Q :", Q)
print(Q/ql.max(Q)*100)

#adexe

state = ql.array([[0, 0, 0, 1, 0, 1]])
print(type(state))
print(ql.asarray(state > 0))

action 1
[[0. 0. 0. 0. 0. 0.]]
bf_Q [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
bf_max_state [0 1 2 3 4 5]
max_state [1]
af_max_state [1]
max_value [[0.]]
reward [[0. 1. 0. 0. 0. 0.]]

curr_state 0
poss_act [1 4]
action 4
bf_Q [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
bf_max_state [0 1 2 3 4 5]
max_state [4]
af_max_state [4]
max_value [[0.]]
reward [[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

curr_state 3
poss_act [1 2 4]
action 4
bf_Q [[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
bf_max_state [0 1 2 3 4 5]
max_state [5]
af_max_state [5]
max_value [[0.]]
reward [[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.